# Response to reviewers

In [35]:
# 1.2
# load all city and source of years
import os
import pandas as pd
import numpy as np

ROOT = r"D:\Dropbox (Personal)\Personal Work\_Projects2023\01_city-never-was"

# ROOT = "/Users/yuan/Dropbox (Personal)/Personal Work/_Projects2023"
EXPORT_FOLDER = f"{ROOT}/_data/_curated/c_analysis"

city_path = os.path.join(EXPORT_FOLDER,
                            f"c_city_built_environment_full_cluster=all_ncat=27.csv")
citydf = pd.read_csv(city_path)

In [36]:
update_folder = f"{ROOT}/_data/_raw/_road_fatality/_fatality/"

In [37]:
fatality_df = pd.read_excel(f"{ROOT}/_data/_raw/_road_fatality/_fatality/data_source_update.xlsx")
fatality_df['city_lower'] = fatality_df['City'].fillna("").str.lower().apply(lambda x: x.replace(" ", ""))
fatality_df.head()

,Region,City,Source,Year Covered,Process Description,city_lower
0,Argentina,Buenos Aires,\cite{argentina_buenos_aires},2015,NaN,buenosaires
1,Australia,Sydney,\cite{australia_sydney},2019,NaN,sydney
2,Austria,Vienna,\cite{austria_vienna},2023,NaN,vienna
3,Bangladesh,Dhaka,\cite{bangladesh_dhaka},2019,NaN,dhaka
4,Belgium,Brussels,\cite{ntua_global_benchmark},2020,NaN,brussels

In [52]:
updatesource = citydf[['city_lower','country','num_person_killed_per_lakh_city','num_hex']]\
    .merge(fatality_df, 
           on = 'city_lower',
           how = 'left').drop_duplicates()
updatesource['Year Covered'] = np.where(
    updatesource['country']=='Brazil', 2019, updatesource['Year Covered'])
updatesource['Year Covered'] = np.where(
    updatesource['country']=='India', 2019, updatesource['Year Covered'])
updatesource['Year Covered'] = np.where(
    updatesource['country']=='India', 2019, updatesource['Year Covered'])
updatesource['Region'] = updatesource['Region'].fillna(updatesource['country'])
updatesource['City'] = updatesource['City'].fillna(updatesource['city_lower'].str.capitalize())
updatesource['Year Covered'] = np.where(
    updatesource['country']=='United States of America', 2019, updatesource['Year Covered'])
updatesource['Region'] = updatesource['Region'].fillna("United States of America")
updatesource = updatesource[~updatesource['city_lower'].isin(['lima', 'chicago'])].reset_index(drop = True)

updatesource['Source'] = np.where(
    updatesource['country']=='Brazil',
    "\cite{malta2022road}",
    updatesource['Source']
)
ussource = "\cite{usa_all_cities}"
indiasource = "\cite{india_all_cities}"
updatesource['Source'] = np.where(
    updatesource['country']=='United States of America',
    ussource,
    updatesource['Source']
)
updatesource['Source'] = np.where(
    updatesource['country']=='India',
    indiasource,
    updatesource['Source']
)
updatesource['Region'] = np.where(
    updatesource['city_lower']=='toledo',
    "United States of America",
    updatesource['Region']
)

updatesource['Year Covered'] = updatesource['Year Covered'].fillna(2019)
updatesource['Source'] = updatesource['Source'].fillna(ussource)

updatesource[['Region', 
              'City', 
              'Year Covered', 
              'num_person_killed_per_lakh_city',
              'Source']].sort_values(['Region','City']).to_csv(os.path.join(update_folder, "city_fatality_source_update.csv"), index = False)

In [56]:
updatesource['num_person_killed_per_lakh_city'].describe()

count    106.000000
mean       9.290377
std        7.608117
min        0.400000
25%        3.262500
50%        6.920000
75%       13.730000
max       33.660000
Name: num_person_killed_per_lakh_city, dtype: float64

In [54]:
updatesource[updatesource['num_hex']==30]

,city_lower,country,num_person_killed_per_lakh_city,num_hex,Region,City,Source,Year Covered,Process Description
41,jalna,India,9.6,30,India,Jalna,\cite{india_all_cities},2019.0,NaN

In [55]:
updatesource['num_hex'].describe()

count      106.000000
mean      2834.226415
std       2543.023365
min         30.000000
25%        955.250000
50%       2061.000000
75%       3924.250000
max      13500.000000
Name: num_hex, dtype: float64

In [47]:
updatesource.groupby('Year Covered').size()

Year Covered
2012.0     1
2014.0     5
2015.0     3
2016.0     4
2018.0     2
2019.0    77
2020.0     5
2021.0     1
2022.0     4
2023.0     4
dtype: int64

In [48]:
test = """
Argentina                & Buenos Aires   & 2015         & 3.7                                  & \textbackslash{}cite\{argentina\_buenos\_aires\}   \\
Australia                & Sydney         & 2019         & 1.4                                  & \textbackslash{}cite\{australia\_sydney\}          \\
Austria                  & Vienna         & 2023         & 0.63                                 & \textbackslash{}cite\{austria\_vienna\}            \\
Bangladesh               & Dhaka          & 2019         & 15.3                                 & \textbackslash{}cite\{bangladesh\_dhaka\}          \\
Belgium                  & Antwerp        & 2020         & 3.48                                 & \textbackslash{}cite\{belgium\_antwerp\}           \\
Belgium                  & Brussels       & 2020         & 3.04                                 & \textbackslash{}cite\{ntua\_global\_benchmark\}    \\
Bolivia                  & Cochabamba     & 2019         & 21.1                                 & \textbackslash{}cite\{who\_observe\}               \\
Brazil                   & Belohorizonte  & 2019         & 18.7                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Curitiba       & 2019         & 23.5                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Florianopolis  & 2019         & 22.6                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Ilheus         & 2019         & 18.7                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Jequie         & 2019         & 18.7                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Palmas         & 2019         & 30.9                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Ribeiraopreto  & 2019         & 13.9                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Riodejaneiro   & 2019         & 15.7                                 & \textbackslash{}cite\{malta2022road\}              \\
Brazil                   & Saopaulo       & 2019         & 13.9                                 & \textbackslash{}cite\{malta2022road\}              \\
Canada                   & Toronto        & 2019         & 2.2                                  & \textbackslash{}cite\{canada\_toronto\}            \\
Canada                   & Victoria       & 2019         & 5                                    & \textbackslash{}cite\{canada\_victoria\}           \\
Chile                    & Santiago       & 2023         & 10.5                                 & \textbackslash{}cite\{chile\_santiago\}            \\
Colombia                 & BogotÃ¡        & 2019         & 7.2                                  & \textbackslash{}cite\{ntua\_global\_benchmark\}    \\
Colombia                 & Valledupar     & 2019         & 12.86                                & \textbackslash{}cite\{nation\_center\}             \\
Denmark                  & Copenhagen     & 2019         & 1.4                                  & \textbackslash{}cite\{ntua\_global\_benchmark\}    \\
Ecuador                  & Quito          & 2020         & 14.8                                 & \textbackslash{}cite\{ecuador\_quito\}             \\
France                   & Paris          & 2016         & 1.8                                  & \textbackslash{}cite\{ntua\_global\_benchmark\}    \\
Germany                  & Berlin         & 2019         & 1.3                                  & \textbackslash{}cite\{germany\_berlin\}            \\
Germany                  & Munich         & 2020         & 1.15                                 & \textbackslash{}cite\{germany\_munich\}            \\
Ghana                    & Accra          & 2019         & 17.24                                & \textbackslash{}cite\{ghana\_accra\}               \\
Greece                   & Athens         & 2019         & 2.2                                  & \textbackslash{}cite\{greece\}                     \\
Greece                   & Thessaloniki   & 2019         & 1.3                                  & \textbackslash{}cite\{greece\}                     \\
Guatemala                & Guatemala City & 2019         & 22.9                                 & \textbackslash{}cite\{who\_observe\}               \\
Hong Kong                & Hong Kong      & 2019         & 1.5                                  & \textbackslash{}cite\{hong\_kong\_hong\_kong\}     \\
Hungary                  & Budapest       & 2023         & 2.47                                 & \textbackslash{}cite\{hungary\_budapest\}          \\
India                    & Bangalore      & 2019         & 17.1                                 & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Delhi          & 2019         & 4.98                                 & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Hindupur       & 2019         & 8.8                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Hyderabad      & 2019         & 2.78                                 & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Jaipur         & 2019         & 33.66                                & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Jalna          & 2019         & 9.6                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Kanpur         & 2019         & 7.9                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Kozhikode      & 2019         & 12.3                                 & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Mumbai         & 2019         & 2.92                                 & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Parbhani       & 2019         & 5.9                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Pune           & 2019         & 9.5                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Sitapur        & 2019         & 9.9                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
India                    & Vijayawada     & 2019         & 8.8                                  & \textbackslash{}cite\{india\_all\_cities\}         \\
Indonesia                & Cirebon        & 2014         & 5.69                                 & \textbackslash{}cite\{indonesia\}                  \\
Indonesia                & Jakarta        & 2014         & 20.93                                & \textbackslash{}cite\{indonesia\}                  \\
Indonesia                & Medan          & 2014         & 13.01                                & \textbackslash{}cite\{indonesia\}                  \\
Indonesia                & Palembang      & 2014         & 14.27                                & \textbackslash{}cite\{indonesia\}                  \\
Indonesia                & Parepare       & 2014         & 5.69                                 & \textbackslash{}cite\{indonesia\}                  \\
Israel                   & Jerusalem      & 2019         & 3.9                                  & \textbackslash{}cite\{WHO\_road\_safety\}          \\
Israel                   & Tel Aviv       & 2019         & 3.9                                  & \textbackslash{}cite\{WHO\_road\_safety\}          \\
Italy                    & Milan          & 2019         & 4.4                                  & \textbackslash{}cite\{italy\_milan\}               \\
Italy                    & Palermo        & 2019         & 4.2                                  & \textbackslash{}cite\{italy\_palermo\}             \\
Italy                    & Rome           & 2019         & 5                                    & \textbackslash{}cite\{italy\_rome\}                \\
Japan                    & Fukuoka        & 2016         & 4.25                                 & \textbackslash{}cite\{japan\}                      \\
Japan                    & Okayama        & 2022         & 3.94                                 & \textbackslash{}cite\{japan\_okayama\}             \\
Japan                    & Tokyo          & 2016         & 1.87                                 & \textbackslash{}cite\{japan\}                      \\
Japan                    & Yamaguchi      & 2016         & 5.93                                 & \textbackslash{}cite\{japan\}                      \\
Kenya                    & Nairobi        & 2019         & 28.3                                 & \textbackslash{}cite\{kenya\_nairobi\}             \\
Lithuania                & Kaunas         & 2018         & 10.84                                & \textbackslash{}cite\{lithuania\_kaunas\}          \\
Malaysia                 & Kuala Lumpur   & 2019         & 11.2                                 & \textbackslash{}cite\{hong\_kong\_hong\_kong\}     \\
Mexico                   & Guadalajara    & 2015         & 24                                   & \textbackslash{}cite\{ntua\_global\_benchmark\}    \\
Mexico                   & Mexico City    & 2015         & 8.7                                  & \textbackslash{}cite\{mexico\_mexico\_city\}       \\
Netherlands              & Amsterdam      & 2019         & 5.05                                 & \textbackslash{}cite\{netherlands\_zwolle\}        \\
Netherlands              & Zwolle         & 2019         & 4.93                                 & \textbackslash{}cite\{netherlands\_zwolle\}        \\
New Zealand              & Auckland       & 2019         & 2.35                                 & \textbackslash{}cite\{new\_zealand\}               \\
New Zealand              & Wellington     & 2019         & 5.17                                 & \textbackslash{}cite\{new\_zealand\}               \\
Nigeria                  & Gombe          & 2022         & 20.87                                & \textbackslash{}cite\{nigeria\_gombe\}             \\
Nigeria                  & Lagos          & 2019         & 12.95                                & \textbackslash{}cite\{nigeria\_lagos\}             \\
Philippines              & Bacolod        & 2019         & 7.3                                  & \textbackslash{}cite\{philippines\_bacolod\}       \\
Philippines              & Cebu City      & 2019         & 28.18                                & \textbackslash{}cite\{philippines\_cebu\_city\}    \\
Philippines              & Metro Manila   & 2019         & 20.9                                 & \textbackslash{}cite\{philippines\_metro\_manila\} \\
Republic of   Korea      & Seoul          & 2023         & 1.9                                  & \textbackslash{}cite\{south\_korea\_seoul\}        \\
Russian     Federation   & Moscow         & 2019         & 3.5                                  & \textbackslash{}cite\{russia\_moscow\}             \\
Rwanda                   & Kigali         & 2012         & 20                                   & \textbackslash{}cite\{rwanda\_kigali\}             \\
Serbia                   & Belgrade       & 2018         & 7                                    & \textbackslash{}cite\{ntua\_global\_benchmark\}    \\
Singapore                & Singapore      & 2019         & 1.5                                  & \textbackslash{}cite\{singapore\_singapore\}       \\
South Africa             & Capetown       & 2019         & 18                                   & \textbackslash{}cite\{nation\_center\}             \\
South Africa             & Johannesburg   & 2019         & 18.5                                 & \textbackslash{}cite\{south\_africa\}              \\
Spain                    & Madrid         & 2019         & 4.93                                 & \textbackslash{}cite\{spain\_madrid\}              \\
Sweden                   & Stockholm      & 2019         & 0.4                                  & \textbackslash{}cite\{report\_hk\}                 \\
Taiwan                   & Taipei         & 2019         & 2.3                                  & \textbackslash{}cite\{report\_hk\}                 \\
Thailand                 & Bangkok        & 2022         & 14.41                                & \textbackslash{}cite\{thailand\_bangkok\}          \\
Turkey                   & Istanbul       & 2019         & 2.38                                 & \textbackslash{}cite\{turkey\_istanbul\}           \\
Uganda                   & Kampala        & 2019         & 12                                   & \textbackslash{}cite\{uganda\_kampala\}            \\
Ukraine                  & Kyiv           & 2019         & 4.75                                 & \textbackslash{}cite\{ukraine\_kyiv\}              \\
United Arab Emirates     & Dubai          & 2022         & 3.6                                  & \textbackslash{}cite\{uae\_dubai\}                 \\
United Kingdom           & London         & 2019         & 1.34                                 & \textbackslash{}cite\{UK\_road\_safety\}           \\
United Kingdom           & Manchester     & 2021         & 2.35                                 & \textbackslash{}cite\{UK\_road\_safety\}           \\
United Kingdom           & Sheffield      & 2020         & 2.23                                 & \textbackslash{}cite\{UK\_road\_safety\}           \\
United States of America & Boston         & 2019         & 3.06                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Cleveland      & 2019         & 6.84                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Denver         & 2019         & 8.58                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Detroit        & 2019         & 9.32                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Houston        & 2019         & 8.91                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Killeen        & 2019         & 11.81                                & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Losangeles     & 2019         & 7.21                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Miami          & 2019         & 11.09                                & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Minneapolis    & 2019         & 3.19                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Modesto        & 2019         & 13.22                                & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Newyork        & 2019         & 2.48                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Philadelphia   & 2019         & 5.71                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Raleigh        & 2019         & 6.62                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Sanfrancisco   & 2019         & 4.58                                 & \textbackslash{}cite\{usa\_all\_cities\}           \\
United States of America & Toledo         & 2019         & 8.14                                 & \textbackslash{}cite\{usa\_all\_cities\} """
# newlines = []
# for i in test.split("\n"):
#     newline = 
test = test.replace("\hline", "").strip().replace("""\textbackslash{}cite\{""", "\cite{").replace("\_", "_").strip().replace("\}", "}")
newlines = []
for i in test.split("\n"):
    newlines.append(i)

In [49]:
print(test)

Argentina                & Buenos Aires   & 2015         & 3.7                                  & \cite{argentina_buenos_aires}   \
Australia                & Sydney         & 2019         & 1.4                                  & \cite{australia_sydney}          \
Austria                  & Vienna         & 2023         & 0.63                                 & \cite{austria_vienna}            \
Bangladesh               & Dhaka          & 2019         & 15.3                                 & \cite{bangladesh_dhaka}          \
Belgium                  & Antwerp        & 2020         & 3.48                                 & \cite{belgium_antwerp}           \
Belgium                  & Brussels       & 2020         & 3.04                                 & \cite{ntua_global_benchmark}    \
Bolivia                  & Cochabamba     & 2019         & 21.1                                 & \cite{who_observe}               \
Brazil                   & Belohorizonte  & 2019         & 18.7                                 & \cite{malta2022road}              \
Brazil                   & Curitiba       & 2019         & 23.5                                 & \cite{malta2022road}              \
Brazil                   & Florianopolis  & 2019         & 22.6                                 & \cite{malta2022road}              \
Brazil                   & Ilheus         & 2019         & 18.7                                 & \cite{malta2022road}              \
Brazil                   & Jequie         & 2019         & 18.7                                 & \cite{malta2022road}              \
Brazil                   & Palmas         & 2019         & 30.9                                 & \cite{malta2022road}              \
Brazil                   & Ribeiraopreto  & 2019         & 13.9                                 & \cite{malta2022road}              \
Brazil                   & Riodejaneiro   & 2019         & 15.7                                 & \cite{malta2022road}              \
Brazil                   & Saopaulo       & 2019         & 13.9                                 & \cite{malta2022road}              \
Canada                   & Toronto        & 2019         & 2.2                                  & \cite{canada_toronto}            \
Canada                   & Victoria       & 2019         & 5                                    & \cite{canada_victoria}           \
Chile                    & Santiago       & 2023         & 10.5                                 & \cite{chile_santiago}            \
Colombia                 & BogotÃ¡        & 2019         & 7.2                                  & \cite{ntua_global_benchmark}    \
Colombia                 & Valledupar     & 2019         & 12.86                                & \cite{nation_center}             \
Denmark                  & Copenhagen     & 2019         & 1.4                                  & \cite{ntua_global_benchmark}    \
Ecuador                  & Quito          & 2020         & 14.8                                 & \cite{ecuador_quito}             \
France                   & Paris          & 2016         & 1.8                                  & \cite{ntua_global_benchmark}    \
Germany                  & Berlin         & 2019         & 1.3                                  & \cite{germany_berlin}            \
Germany                  & Munich         & 2020         & 1.15                                 & \cite{germany_munich}            \
Ghana                    & Accra          & 2019         & 17.24                                & \cite{ghana_accra}               \
Greece                   & Athens         & 2019         & 2.2                                  & \cite{greece}                     \
Greece                   & Thessaloniki   & 2019         & 1.3                                  & \cite{greece}                     \
Guatemala                & Guatemala City & 2019         & 22.9                                 & \cite{who_observe}               \
Hong Kong                & Hong Kong      & 2019         & 1.5                                  & \cite{hong_kong_hong_kong}     \
Hungary                  & Budapest       & 2023         & 2.47                                 & \cite{hungary_budapest}          \
India                    & Bangalore      & 2019         & 17.1                                 & \cite{india_all_cities}         \
India                    & Delhi          & 2019         & 4.98                                 & \cite{india_all_cities}         \
India                    & Hindupur       & 2019         & 8.8                                  & \cite{india_all_cities}         \
India                    & Hyderabad      & 2019         & 2.78                                 & \cite{india_all_cities}         \
India                    & Jaipur         & 2019         & 33.66                                & \cite{india_all_cities}         \
India                    & Jalna          & 2019         & 9.6                                  & \cite{india_all_cities}         \
India                    & Kanpur         & 2019         & 7.9                                  & \cite{india_all_cities}         \
India                    & Kozhikode      & 2019         & 12.3                                 & \cite{india_all_cities}         \
India                    & Mumbai         & 2019         & 2.92                                 & \cite{india_all_cities}         \
India                    & Parbhani       & 2019         & 5.9                                  & \cite{india_all_cities}         \
India                    & Pune           & 2019         & 9.5                                  & \cite{india_all_cities}         \
India                    & Sitapur        & 2019         & 9.9                                  & \cite{india_all_cities}         \
India                    & Vijayawada     & 2019         & 8.8                                  & \cite{india_all_cities}         \
Indonesia                & Cirebon        & 2014         & 5.69                                 & \cite{indonesia}                  \
Indonesia                & Jakarta        & 2014         & 20.93                                & \cite{indonesia}                  \
Indonesia                & Medan          & 2014         & 13.01                                & \cite{indonesia}                  \
Indonesia                & Palembang      & 2014         & 14.27                                & \cite{indonesia}                  \
Indonesia                & Parepare       & 2014         & 5.69                                 & \cite{indonesia}                  \
Israel                   & Jerusalem      & 2019         & 3.9                                  & \cite{WHO_road_safety}          \
Israel                   & Tel Aviv       & 2019         & 3.9                                  & \cite{WHO_road_safety}          \
Italy                    & Milan          & 2019         & 4.4                                  & \cite{italy_milan}               \
Italy                    & Palermo        & 2019         & 4.2                                  & \cite{italy_palermo}             \
Italy                    & Rome           & 2019         & 5                                    & \cite{italy_rome}                \
Japan                    & Fukuoka        & 2016         & 4.25                                 & \cite{japan}                      \
Japan                    & Okayama        & 2022         & 3.94                                 & \cite{japan_okayama}             \
Japan                    & Tokyo          & 2016         & 1.87                                 & \cite{japan}                      \
Japan                    & Yamaguchi      & 2016         & 5.93                                 & \cite{japan}                      \
Kenya                    & Nairobi        & 2019         & 28.3                                 & \cite{kenya_nairobi}             \
Lithuania                & Kaunas         & 2018         & 10.84                                & \cite{lithuania_kaunas}          \
Malaysia                 & Kuala Lumpur   & 2019         & 11.2                                 & \cite{hong_kong_hong_kong}     \
Mexico                   & Guadalajara    & 2015         & 24                                   & \cite{ntua_global_benchmark}    \
Mexico                   & Mexico City    & 2015         & 8.7                                  & \cite{mexico_mexico_city}       \
Netherlands              & Amsterdam      & 2019         & 5.05                                 & \cite{netherlands_zwolle}        \
Netherlands              & Zwolle         & 2019         & 4.93                                 & \cite{netherlands_zwolle}        \
New Zealand              & Auckland       & 2019         & 2.35                                 & \cite{new_zealand}               \
New Zealand              & Wellington     & 2019         & 5.17                                 & \cite{new_zealand}               \
Nigeria                  & Gombe          & 2022         & 20.87                                & \cite{nigeria_gombe}             \
Nigeria                  & Lagos          & 2019         & 12.95                                & \cite{nigeria_lagos}             \
Philippines              & Bacolod        & 2019         & 7.3                                  & \cite{philippines_bacolod}       \
Philippines              & Cebu City      & 2019         & 28.18                                & \cite{philippines_cebu_city}    \
Philippines              & Metro Manila   & 2019         & 20.9                                 & \cite{philippines_metro_manila} \
Republic of   Korea      & Seoul          & 2023         & 1.9                                  & \cite{south_korea_seoul}        \
Russian     Federation   & Moscow         & 2019         & 3.5                                  & \cite{russia_moscow}             \
Rwanda                   & Kigali         & 2012         & 20                                   & \cite{rwanda_kigali}             \
Serbia                   & Belgrade       & 2018         & 7                                    & \cite{ntua_global_benchmark}    \
Singapore                & Singapore      & 2019         & 1.5                                  & \cite{singapore_singapore}       \
South Africa             & Capetown       & 2019         & 18                                   & \cite{nation_center}             \
South Africa             & Johannesburg   & 2019         & 18.5                                 & \cite{south_africa}              \
Spain                    & Madrid         & 2019         & 4.93                                 & \cite{spain_madrid}              \
Sweden                   & Stockholm      & 2019         & 0.4                                  & \cite{report_hk}                 \
Taiwan                   & Taipei         & 2019         & 2.3                                  & \cite{report_hk}                 \
Thailand                 & Bangkok        & 2022         & 14.41                                & \cite{thailand_bangkok}          \
Turkey                   & Istanbul       & 2019         & 2.38                                 & \cite{turkey_istanbul}           \
Uganda                   & Kampala        & 2019         & 12                                   & \cite{uganda_kampala}            \
Ukraine                  & Kyiv           & 2019         & 4.75                                 & \cite{ukraine_kyiv}              \
United Arab Emirates     & Dubai          & 2022         & 3.6                                  & \cite{uae_dubai}                 \
United Kingdom           & London         & 2019         & 1.34                                 & \cite{UK_road_safety}           \
United Kingdom           & Manchester     & 2021         & 2.35                                 & \cite{UK_road_safety}           \
United Kingdom           & Sheffield      & 2020         & 2.23                                 & \cite{UK_road_safety}           \
United States of America & Boston         & 2019         & 3.06                                 & \cite{usa_all_cities}           \
United States of America & Cleveland      & 2019         & 6.84                                 & \cite{usa_all_cities}           \
United States of America & Denver         & 2019         & 8.58                                 & \cite{usa_all_cities}           \
United States of America & Detroit        & 2019         & 9.32                                 & \cite{usa_all_cities}           \
United States of America & Houston        & 2019         & 8.91                                 & \cite{usa_all_cities}           \
United States of America & Killeen        & 2019         & 11.81                                & \cite{usa_all_cities}           \
United States of America & Losangeles     & 2019         & 7.21                                 & \cite{usa_all_cities}           \
United States of America & Miami          & 2019         & 11.09                                & \cite{usa_all_cities}           \
United States of America & Minneapolis    & 2019         & 3.19                                 & \cite{usa_all_cities}           \
United States of America & Modesto        & 2019         & 13.22                                & \cite{usa_all_cities}           \
United States of America & Newyork        & 2019         & 2.48                                 & \cite{usa_all_cities}           \
United States of America & Philadelphia   & 2019         & 5.71                                 & \cite{usa_all_cities}           \
United States of America & Raleigh        & 2019         & 6.62                                 & \cite{usa_all_cities}           \
United States of America & Sanfrancisco   & 2019         & 4.58                                 & \cite{usa_all_cities}           \
United States of America & Toledo         & 2019         & 8.14                                 & \cite{usa_all_cities}

test = """
"""